### ISSUE TITLE
Visit counter

### ISSUE THREAD

**Issue by stricktech** [llmexplorer/inflationfast#1]
The visit counter will count 1 person more than 1 time, if they refresh or Reload they page. (Each refresh = 1 visit), would recommend modification to only count unique visits.

**Comment by llmexplorer** [comment]
Thanks for the feedback.  In this case the counter updates in memory (so you can verify that the counter is working) but only unique visits (by IP address) are persisted in the database.  The counter resets every 5 days when the update script runs, or more frequently if I reset the server.
